modLoader="javafml" #mandatory
loaderVersion="[47,)"
license="MIT License https://github.com/McJty/Wastify/blob/1.19/LICENCE"

[[mods]]
modId="wastify"
version="${file.jarVersion}"
displayName="Wastify"
authors="McJty"
description='''
Wastify will change biomes to your own desired mapping
'''
[[dependencies.wastify]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.wastify]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"